### PR TITLE
Added a ToC in README.md

### PR DESCRIPTION
**Pull request by IOAyman**
The `README.md` file is a little lengthy, it would be nice to easily go to what you're looking for in the documentation.

### CODE REVIEW

**Comment by IOAyman** [comment]
For reference, [this tool](https://imthenachoman.github.io/nGitHubTOC/) could be used to easily update the table in case of major changes to the documentation in the future.

**Comment by mbrt** [comment]
Thanks for your contribution!

I was planning to cleanup a bit this README, but having a TOC in the meantime sounds good!
It would be nice if there was a way to add a test that fails if the TOC gets out of sync. Do you know of a way to do that?

**Comment by browniebroke** [comment]
I recently stumbled upon this GitHub action to generate it: https://github.com/technote-space/toc-generator

**Comment by mbrt** [comment]
Ah thanks! I can maybe add tests for this as a follow up. I'll merge this for now.

**Pull request merged**
